# Generated by Django 4.2.4 on 2023-10-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='nome',
            new_name='titulo',
        ),
    ]
