# Generated by Django 4.2.4 on 2023-10-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_tarefa_descricao_tarefa_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa')], default='V', max_length=5),
        ),
    ]
