# Generated by Django 4.2.4 on 2023-10-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_tarefa_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Concluida', 'Concluida'), ('Andamento', 'Andamento'), ('Pendente', 'Pendente')], default='P', max_length=10),
        ),
    ]
